"""add email table

Revision ID: 068f86bb8fb8
Revises: f51da0a0dc3f
Create Date: 2024-08-13 14:39:39.642450

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "068f86bb8fb8"
down_revision: Union[str, None] = "f51da0a0dc3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_emails_email"), "emails", ["email"], unique=True)
    op.create_index(op.f("ix_emails_id"), "emails", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ##
    op.drop_index(op.f("ix_emails_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_email"), table_name="emails")
    op.drop_table("emails")
    # ### end Alembic commands ###
