"""add cost to adjustment table

Revision ID: 166995855332
Revises: ee71bb9361fe
Create Date: 2024-09-27 12:08:17.183867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166995855332'
down_revision: Union[str, None] = 'ee71bb9361fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_adjustments', sa.Column('cost', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_adjustments', 'cost')
    # ### end Alembic commands ###
