"""change schema definition

Revision ID: 46078c99f53b
Revises: 535bff041ea5
Create Date: 2024-10-16 14:52:20.527495

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46078c99f53b"
down_revision: Union[str, None] = "535bff041ea5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "purchase_order_items",
        sa.Column("purchase_order_id", sa.Integer(), nullable=False),
    )
    op.create_unique_constraint(None, "purchase_order_items", ["id"])
    op.create_foreign_key(
        None, "purchase_order_items", "purchase_orders", ["purchase_order_id"], ["id"]
    )
    op.create_unique_constraint(None, "purchase_order_types", ["id"])
    op.create_unique_constraint(None, "purchase_orders", ["id"])
    op.drop_constraint(
        "purchase_orders_purchase_order_item_ids_fkey",
        "purchase_orders",
        type_="foreignkey",
    )
    op.drop_column("purchase_orders", "purchase_order_item_ids")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "purchase_orders",
        sa.Column(
            "purchase_order_item_ids", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "purchase_orders_purchase_order_item_ids_fkey",
        "purchase_orders",
        "purchase_order_items",
        ["purchase_order_item_ids"],
        ["id"],
    )
    op.drop_constraint(None, "purchase_orders", type_="unique")
    op.drop_constraint(None, "purchase_order_types", type_="unique")
    op.drop_constraint(None, "purchase_order_items", type_="foreignkey")
    op.drop_constraint(None, "purchase_order_items", type_="unique")
    op.drop_column("purchase_order_items", "purchase_order_id")
    # ### end Alembic commands ###
