"""add cancelled to stock

Revision ID: 8c3aa1b58f6d
Revises: 45e5361c6aa6
Create Date: 2024-10-28 13:35:51.084079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3aa1b58f6d'
down_revision: Union[str, None] = '45e5361c6aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('cancelled', sa.Boolean(), nullable=True))
 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'cancelled')
    