"""remove cost table

Revision ID: 9236bc8a57ad
Revises: 7a2af8d96d8e
Create Date: 2024-09-18 11:45:26.202303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9236bc8a57ad'
down_revision: Union[str, None] = '7a2af8d96d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_costs_id', table_name='costs')
    op.execute("DROP TABLE costs CASCADE")
    op.add_column('stocks', sa.Column('cost', sa.Float(),
                  nullable=False, server_default="0"))
    op.drop_column('stocks', 'cost_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('cost_id', sa.INTEGER(),
                  autoincrement=False, nullable=False))
    op.drop_column('stocks', 'cost')
    op.create_table('costs',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='costs_pkey'),
                    sa.UniqueConstraint('cost', name='costs_cost_key')
                    )
    op.create_index('ix_costs_id', 'costs', ['id'], unique=False)
    # ### end Alembic commands ###
