"""add cancel feature and stock id to purchase order item

Revision ID: 95f600a625ff
Revises: a228729d0f42
Create Date: 2024-10-17 12:41:30.076799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f600a625ff'
down_revision: Union[str, None] = 'a228729d0f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('stock_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_order_items', 'stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'stock_id')
    # ### end Alembic commands ###
