"""change schema definition

Revision ID: a228729d0f42
Revises: 46078c99f53b
Create Date: 2024-10-16 14:57:01.822915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a228729d0f42'
down_revision: Union[str, None] = '46078c99f53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('requested_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_order_items', 'staffs', ['requested_by'], ['id'])
    op.drop_constraint('purchase_orders_requested_by_fkey', 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'requested_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('purchase_orders_requested_by_fkey', 'purchase_orders', 'staffs', ['requested_by'], ['id'])
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_column('purchase_order_items', 'requested_by')
    # ### end Alembic commands ###
