"""add quantity initiated

Revision ID: d38a422a0c21
Revises: a2ec792d1fb5
Create Date: 2024-09-06 11:09:26.028223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd38a422a0c21'
down_revision: Union[str, None] = 'a2ec792d1fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('quantity_initiated', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'quantity_initiated')
    # ### end Alembic commands ###
