"""add payment terms

Revision ID: e726bd94f2cb
Revises: 95f600a625ff
Create Date: 2024-10-21 11:17:25.333214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e726bd94f2cb'
down_revision: Union[str, None] = '95f600a625ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_terms',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('num_of_days', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    
    op.add_column('purchase_orders', sa.Column(
        'payment_term_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'purchase_orders', 'payment_terms', [
                          'payment_term_id'], ['id'])
    op.drop_column('purchase_orders', 'payment_terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('payment_terms',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'payment_term_id')
    op.drop_table('payment_terms')
    # ### end Alembic commands ###
