"""add cost to running stock

Revision ID: ee71bb9361fe
Revises: 9236bc8a57ad
Create Date: 2024-09-19 16:03:39.248084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee71bb9361fe'
down_revision: Union[str, None] = '9236bc8a57ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_runnings', sa.Column('cost', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_runnings', 'cost')
    # ### end Alembic commands ###
