"""generate category data

Revision ID: f0a7513d9f51
Revises: bdaed69c3df2
Create Date: 2024-09-13 22:50:03.443296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a7513d9f51'
down_revision: Union[str, None] = 'bdaed69c3df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), unique=True, nullable=False),
                    sa.Column('name', sa.String(),
                              nullable=False, unique=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_categories_id'),
                    'categories', ['id'], unique=True)
    op.create_index(op.f('ix_categories_name'),
                    'categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    # ### end Alembic commands ###
