"""add tables

Revision ID: f51da0a0dc3f
Revises: 
Create Date: 2024-08-13 13:53:58.244233

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from models.roles import Roles
from utils.enum import RolesStatus

# revision identifiers, used by Alembic.
revision: str = "f51da0a0dc3f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "barcode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("specification", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_barcode_barcode"), "barcode", ["barcode"], unique=True)
    op.create_index(op.f("ix_barcode_code"), "barcode", ["code"], unique=False)
    op.create_index(op.f("ix_barcode_id"), "barcode", ["id"], unique=True)
    op.create_table(
        "costs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cost"),
    )
    op.create_index(op.f("ix_costs_id"), "costs", ["id"], unique=True)
    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_department_id"), "department", ["id"], unique=True)
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_job_id"), "job", ["id"], unique=True)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("engineer", "stock_controller", name="rolesstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("staff_id_number", sa.String(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("hash_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_staff_id"), "staff", ["id"], unique=True)
    op.create_index(
        op.f("ix_staff_staff_id_number"), "staff", ["staff_id_number"], unique=True
    )
    op.create_table(
        "stock_running",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode_id", sa.Integer(), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), nullable=False),
        sa.Column("out_quantity", sa.Integer(), nullable=False),
        sa.Column("adjustment_quantity", sa.Integer(), nullable=False),
        sa.Column("remaining_quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("available", "re_order", name="runningstockstatus"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_id"],
            ["barcode.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_running_id"), "stock_running", ["id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("staff_id", sa.Integer(), nullable=True),
        sa.Column("barcode_id", sa.Integer(), nullable=False),
        sa.Column("job_number", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("available_quantity", sa.Integer(), nullable=True),
        sa.Column(
            "restrictions",
            sa.Enum("part_not_available", "part_available", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_id"],
            ["barcode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=True)
    op.create_table(
        "stock",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("sold", sa.Boolean(), nullable=True),
        sa.Column("cost_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_id"],
            ["barcode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cost_id"],
            ["costs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_id"), "stock", ["id"], unique=True)
    op.create_table(
        "stock_adjustments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("barcode_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_id"],
            ["barcode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["staff.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["staff.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_adjustments_id"), "stock_adjustments", ["id"], unique=True
    )
    op.create_table(
        "stock_out",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("barcode_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["barcode_id"],
            ["barcode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stock_out_id"), "stock_out", ["id"], unique=True)
    op.bulk_insert(
        Roles.__table__,
        rows=[
            {"id": 1, "name": RolesStatus.engineer.name},
            {"id": 2, "name": RolesStatus.stock_controller.name},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_out_id"), table_name="stock_out")
    op.drop_table("stock_out")
    op.drop_index(op.f("ix_stock_adjustments_id"), table_name="stock_adjustments")
    op.drop_table("stock_adjustments")
    op.drop_index(op.f("ix_stock_id"), table_name="stock")
    op.drop_table("stock")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_stock_running_id"), table_name="stock_running")
    op.drop_table("stock_running")
    op.drop_index(op.f("ix_staff_staff_id_number"), table_name="staff")
    op.drop_index(op.f("ix_staff_id"), table_name="staff")
    op.drop_table("staff")
    op.drop_table("roles")
    op.drop_index(op.f("ix_job_id"), table_name="job")
    op.drop_table("job")
    op.drop_index(op.f("ix_department_id"), table_name="department")
    op.drop_table("department")
    op.drop_index(op.f("ix_costs_id"), table_name="costs")
    op.drop_table("costs")
    op.drop_index(op.f("ix_barcode_id"), table_name="barcode")
    op.drop_index(op.f("ix_barcode_code"), table_name="barcode")
    op.drop_index(op.f("ix_barcode_barcode"), table_name="barcode")
    op.drop_table("barcode")
    # ### end Alembic commands ###
